# Generated by Django 5.2.8 on 2026-04-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
