# Generated by Django 5.2.8 on 2026-04-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_country_name_alter_person_country_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['gender'], name='api_person_gender_851d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['age'], name='api_person_age_ecfb3b_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['country_id'], name='api_person_country_06a07b_idx'),
        ),
    ]
