# Generated by Django 5.2.8 on 2026-05-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_person_sample_size'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['age_group'], name='api_person_age_gro_3b7b78_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['created_at'], name='api_person_created_462917_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['gender_probability'], name='api_person_gender__2a3ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['country_probability'], name='api_person_country_5311bf_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['country_id', 'gender', 'age'], name='api_person_country_86b7a0_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['country_id', 'age_group'], name='api_person_country_720fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['gender', 'age'], name='api_person_gender_e42975_idx'),
        ),
    ]
